@startuml ci-cd-system-architecture-scheme

title CI/CD system architecture scheme

card HttpPipelineTriggers as "HTTP Pipeline triggers" {
  agent gitPush as "Git push"
  agent defaultBranchMerge as "Merging another branch to the default branch"
  agent httpRequest as "Http request to pipeline add / retry endpoint"
}


frame CiCDSystem as "CI/CD System"{
    port http as "http"

    component TriggerListener as "Pipeline triggers listeners" {
        card HttpTriggerListener
    }

    component RunnersRegistry  as "Runners and jobs registry" {
        collections Runners as "Runners collections"
        collections Jobs as "Jobs collection"

        queue RunnersQueue as "RunnersQueue"
        queue JobsQueue as "Jobs queue"

        card RunnersManager as "Runners and jobs management" {
            card RegisterRunner
            card DeleteRunner
            card VerifyRunner
            card JobRequest
            card JobUpdate
        }
    }

    component PipelinesRegistry as "Pipelines registry" {
        card PipelineManager as "Pipelines manager" {
            card RegisterPipeline
            card RetryPipeline
            card CancelPipeline
        }
        card PipelineQueueProcessor as "Pipeline queue processor" {
            collections pipelines as "Pipelines collection"
            queue PipelineQueue as "Pipelines queue"
        }
    }

    database Database as "CI/CD System database" {
        entity pipeline
        entity configuration
    }
}

gitPush -> http
defaultBranchMerge -> http
httpRequest -> http

http->>HttpTriggerListener: Register pipeline
HttpTriggerListener ..> Database
HttpTriggerListener -> PipelineManager: Actions to pipelines registry (Creation, retrying and cancelation)
PipelineManager ->> pipelines
PipelineManager ..> Database

pipelines -> PipelineQueue
pipelines ..> Database: Changes to jobs status
PipelineQueue ..> Database: Job statuses updates

legend
Runner - Single executor to run a job and trigger registry changes.
Job - Single job with pipeline execution and eg. logs processing.
Pipeline - Instructions steps to be executed within a single job
endlegend
@enduml