services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  pipeline_assembler:
      class: App\Pipeline\Assembler

  pipeline_schema_validator:
      class: App\Pipeline\SchemaValidator
      arguments: ['%env(PIPELINE_PATH)%']

  pipeline_factory:
      class: App\Pipeline\PipelineFactory
      arguments: ['@pipeline_schema_validator', '@pipeline_assembler', '%env(PIPELINE_PATH)%']

  pipeline_command:
      class: App\Command\RunPipelineCommand
      calls:
        - [setUpFactory, ['@pipeline_factory']]

  Application:
    class: Application
    arguments: [['@pipeline_command']]
    public: true